name: CI

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - run: cargo fmt --check

    - run: cargo build --verbose
    - run: cargo test --verbose
    - run: cargo doc

    # example/hello
    - run: cd example/hello && cargo build --verbose
    - run: cd example/hello && cargo build --release
    - run: |
        tar --zstd -cvf hello_release_x86_64-unknown-linux-gnu.tar.zst \
        example/hello/target/release/hello
    - uses: actions/upload-artifact@v4
      with:
        name: hello_release_x86_64-unknown-linux-gnu
        path: hello_release_x86_64-unknown-linux-gnu.tar.zst
